# Copyright (c) 2023 Rafael Farias
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: Release container
on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t educa_utf_pocketbase .
      - name: Add tags to image
        run: |
          docker tag educa_utf_pocketbase zrafaf/educa_utf_pocketbase:${{ github.event.pull_request.title }}
          docker tag educa_utf_pocketbase zrafaf/educa_utf_pocketbase
      - name: Push Docker image
        run: |
          docker push zrafaf/educa_utf_pocketbase:${{ github.event.pull_request.title }}
          docker push zrafaf/educa_utf_pocketbase
